### ISSUE TITLE
General TO-DO list

### ISSUE THREAD

**Issue by sarangjo** [sarangjo/paper-telephone#4]
- [ ] Make sure game flow works
- [ ] (@sarangjo) finish the refactoring
- [ ] Resolve TODO comments
- [ ] Add color/erasing features
- [ ] Add local WIFI as a network option
- [ ] Handle leaving mid-game, especially from 3 to 2 players (no longer valid game)
